name: apk
on:
  push:
    branches:
      - main

jobs:
  build_apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          distribution: 'temurin'
          java-version: '17'

      - run: echo "JAVA_HOME=${{ env.JAVA_HOME_17_X64 }}" >> $GITHUB_ENV

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'

      - run: flutter pub get
      - run: flutter pub global activate gradle_wrapper
      - run: flutter build apk --release --split-per-abi --tree-shake-icons

      - uses: ncipollo/release-action@v1
        with:
          tag: v1.0.${{ github.run_number }}
          name: "Release v1.0.${{ github.run_number }}"
          body: "🚀 New APK Build!"
          artifacts: build/app/outputs/flutter-apk/*.apk
          token: ${{ secrets.GITHUB_TOKEN }}
